language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod install
    - xctool -workspace DDGFoundation.xcworkspace -scheme DDGFoundationTests test -sdk iphonesimulator